### ISSUE TITLE
Eventing first steps

### ISSUE THREAD

**Issue by odacremolbap** [AmanSarraf/Go-Project#13]
Install Knative Eventing on a cluster that has already installed Knative Serving.
Eventing can work without serving, but we will probably use some Kn services.
Then create an event flow

- [x] [Install eventing](https://knative.dev/docs/install/yaml-install/eventing/install-eventing-with-yaml/)
- [x] Choose In-Memory channel
- [x] Choose MT-Based broker
- [x] Create a namespace called `aman`
- [x] [Create a broker](https://knative.dev/docs/eventing/broker/create-mtbroker/) at the namespace
- [x] [Create a pingsource object](https://knative.dev/docs/eventing/sources/ping-source/) that points to the broker.
- [x] Create a sockeye Knative service.
- [x] [Create a trigger](https://knative.dev/docs/eventing/broker/triggers/) that references the broker to pick events from it, and sinks the events to the pingsource object

**Comment by AmanSarraf** [comment]
![2022-07-12_13-25](https://user-images.githubusercontent.com/90839355/178439195-45574779-6c7e-410d-8157-6c35471ed274.png)

please review @odacremolbap
