### ISSUE TITLE
Create Go Application that produces CloudEvents periodically

### ISSUE THREAD

**Issue by odacremolbap** [AmanSarraf/Go-Project#16]
Create a go application that:

- Contains an infinite loop that sleeps for 10 seconds then emits a CloudEvent to a location using HTTP bindings.
- The location must be configurable using environment variables.
- The CloudEvent type attribute is configurable using environment variables.
- When a CloudEvent is sent a log entry is written to the console.
- If the CloudEvent fails to be sent an entry containing the error is written to the console.

**Comment by AmanSarraf** [comment]
resolved with https://github.com/AmanSarraf/Go-Project/pull/17/commits/6f693773e55301e6ae142c3c64892042268e4ba2

**Comment by AmanSarraf** [comment]
please review @odacremolbap
