### ISSUE TITLE
Non Gorilla version of BookJSON

### ISSUE THREAD

**Issue by odacremolbap** [AmanSarraf/Go-Project#5]
Can you create a version of [this binary](https://github.com/AmanSarraf/Go-Project/blob/main/Projects/BookJSON/main.go) that does not use gorilla, but the "net/http" package directly?

**Comment by AmanSarraf** [comment]
complete with commit https://github.com/AmanSarraf/Go-Project/commit/3eb1574121da426227039281195cba7af995a631
